// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PipelineHealthMonitor.Data;

#nullable disable

namespace PipelineHealthMonitor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PipelineHealthMonitor.Models.Pipeline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("SinkSystem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("sink_system");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("source_system");

                    b.HasKey("Id");

                    b.ToTable("pipelines", (string)null);
                });

            modelBuilder.Entity("PipelineHealthMonitor.Models.PipelineRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("ended_at");

                    b.Property<int>("PipelineId")
                        .HasColumnType("int")
                        .HasColumnName("pipeline_id");

                    b.Property<int>("RecordsFailed")
                        .HasColumnType("int")
                        .HasColumnName("records_failed");

                    b.Property<int>("RecordsRead")
                        .HasColumnType("int")
                        .HasColumnName("records_read");

                    b.Property<int>("RecordsWritten")
                        .HasColumnType("int")
                        .HasColumnName("records_written");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("TriggeredBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("triggered_by");

                    b.HasKey("Id");

                    b.HasIndex("PipelineId")
                        .HasDatabaseName("IX_pipeline_runs_pipeline_id");

                    b.ToTable("pipeline_runs", null, t =>
                        {
                            t.HasCheckConstraint("CK_pipeline_runs_status", "status IN ('RUNNING', 'SUCCESS', 'FAILED', 'PARTIAL')");
                        });
                });

            modelBuilder.Entity("PipelineHealthMonitor.Models.RunError", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("error_code");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("error_message");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("occurred_at");

                    b.Property<int>("RunId")
                        .HasColumnType("int")
                        .HasColumnName("run_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("severity");

                    b.HasKey("Id");

                    b.HasIndex("RunId")
                        .HasDatabaseName("IX_run_errors_run_id");

                    b.ToTable("run_errors", null, t =>
                        {
                            t.HasCheckConstraint("CK_run_errors_severity", "severity IN ('INFO', 'WARNING', 'CRITICAL')");
                        });
                });

            modelBuilder.Entity("PipelineHealthMonitor.Models.PipelineRun", b =>
                {
                    b.HasOne("PipelineHealthMonitor.Models.Pipeline", "Pipeline")
                        .WithMany("Runs")
                        .HasForeignKey("PipelineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pipeline");
                });

            modelBuilder.Entity("PipelineHealthMonitor.Models.RunError", b =>
                {
                    b.HasOne("PipelineHealthMonitor.Models.PipelineRun", "Run")
                        .WithMany("Errors")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("PipelineHealthMonitor.Models.Pipeline", b =>
                {
                    b.Navigation("Runs");
                });

            modelBuilder.Entity("PipelineHealthMonitor.Models.PipelineRun", b =>
                {
                    b.Navigation("Errors");
                });
#pragma warning restore 612, 618
        }
    }
}
